### PR TITLE
fix: guard against missing data elements by using lodash.get

### LINKED ISSUE #18: Handle missing values in the preview
### Motivation
The app crashes unexpectedly in the preview mode for articles without the image or products without the price. Preview Delivery API returns items in the draft step and some values can be missing (even required fields).

### Proposed solution
- The app should handle missing values and display some placeholder without data or with some explanation (e.g,. "Price TBA")
- check other possible occurences of this problem

### Additional context
image
- you can find some inspiration in the[ .NET sample app](https://github.com/Kentico/cloud-sample-app-net)
- related [cloud-sample-app-react issue](https://github.com/Kentico/cloud-sample-app-react/issues/115)

### PR DESCRIPTION
**Pull request by fluffynuts**
### Motivation

Which issue does this fix? Fixes #18 (perhaps only partially -- I used lodash, which was already referenced by the project; if this approach is acceptable, it could be applied elsewhere)

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added (I don't see any existing testing?)
- [ ] Tests are passing
- [ ] Docu has been updated (if applicable)
- [ ] Temporary settings (e.g. project ID used during development and testing) have been reverted to defaults

### How to test

Should solve the problem with partial data causing dereference errors in Articles and Article components

### CODE REVIEW

**Comment by petrsvihlik** [comment]
thanks for the PR, @fluffynuts ! we're on it :)

**Comment by Simply007** [comment]
Hello @fluffynuts,

when I run the application and open articles. I got an error:

```
TypeError: Cannot read property 'formatDate' of undefined
    at mapArticle (MapArticle.js?4863:7)
    ...
```

That is caused by the extraction of `mapArticle` to the separate module and this is not a component you are calling it from. 
* Personally, I would prefer to have all the utility functions to be the pure functions and to not depend on context (this context in that case).

# Ideal case 
Have a universal solver module that would resolve the path to an object or return the localized string. Lodash offers that functionality with combination with VueI18n from [vue-i18n](https://www.npmjs.com/package/vue-i18n) which is already used in application
```
// For resolution of i.e. title.value of the article in Articles component
_.get(article, 'title.value', $t('Articles.notitlevalue'))
```
And have the record in `src/Localization/en-US.json` and `src/Localization/es-ES.json` in format:
```
// Format
{
{
    "locale": "en-US",
     ...
    "Articles": { // component name
        "notitlevalue": "(Article has no title)"
    }
   ...
```

I am OK to use this on article + articles  as a showcase and I would raise the oissue to implement is for the rest of the components.

If anything is unclear, feel free to ask @fluffynuts!

**Comment by fluffynuts** [comment]
I hope this is more in line with what you'd prefer?
1. apologies about the rogue `this`. I don't have a Kentico site to test against -- so this is a good case for code review (:
2. apologies for missing i18n -- it's so important to use it throughout when an app is supposed to have translations

File: src/components/Articles.vue [hunk 1]
```diff
@@ -49,13 +52,7 @@ export default {
...
   computed: {
     articlesData: function() {
-      return this.articles.map(article => ({
-        title: article.title.value,
-        imageLink: article.teaserImage.value[0].url,
-        postDate: this.formatDate(article.postDate.value),
-        summary: article.summary.value,
-        link: `/${this.language}/articles/${article.system.id}`
-      }));
+      return this.articles.map(mapArticle, this.formatDate.bind(this), this.$t.bind(this));
```
Comment (Simply007) [inline src/components/Articles.vue]: The syntax you are using is passing the arguments different way, I would prefer this syntax:

```suggestion
      return this.articles.map(article => mapArticle(article, this.formatDate.bind(this), this.$i18n.t.bind(this)));
```

Unfortunately, it seems it is not possible to use translation out of the component file, beacuse of this issue probably:
* https://github.com/kazupon/vue-i18n/issues/259

So let's map the article separately in Articles and Article component. Here is a sample hot to do it in Articles component.

```suggestion
      return this.articles.map(article => ({
        title: _.get(article, "title.value", this.$i18n.t("Articles.noTitleValue")),
        imageLink: _.get(article, "teaserImage.value[0].url"),
        postDate: this.formatDate(_.get(article, "postDate.value")),
        summary: _.get(article, "summary.value", this.$i18n.t("Articles.noSummaryValue")),
        link: `/${this.language}/articles/${_.get(article, "system.id")}`
      }));
```

**Comment by Simply007** [comment]
Hello @fluffynuts,

for the testing purposes it is possible to generate your own project and then modify Client.js to use the preview API.

Basically what you would do is:
1. run `npm install`
2. run `npm run serve`
3. App should show the configuration page (if not you have already project ID set in cookies - just delete prijectId from cookies and refresh or go to /Administration/Configuration page)
    * Hit Get Project ID from Kentico Cloud
    * Hit Create a sample project
4. After the new project is generated app should display its content
5. Edit Client.js and place projectId and preview API key as described [here] https://github.com/Kentico/cloud-sample-app-vue#connecting-to-your-project-manually

Please see the inline comments in code.

File: src/components/Articles.vue (hunk 1 above)
Comment (fluffynuts) [reply src/components/Articles.vue]: looking at https://github.com/kazupon/vue-i18n/issues/259, the issue stems out of the author not binding a context for `this` to his reference to `$t`, which this PR does do -- I wouldn't expect to be able to do:
```js
var fn = this.$t;
fn("some string");
```
the call to `fn` _should_ reasonably break as it's missing the context and could well refer to `this` within the function.

So the question comes down to which one is preferable:
1. local mappings in each consumer component, with duplicated code and no context binding
2. consolidation of common code in the `mapArticle` function, with bound functions passed in for date formatting & translation

I've tested with the latter, using a Kentico Cloud account, and my last updates work nicely, so it's down to the preference of style for this project. Thoughts?

**Comment by Simply007** [comment]
Hey @fluffynuts,

we would like to thank you for contributing to Kentico's open-source project. As a sign of our appreciation, we would like to send you some [Kentico Developer Community SWAG](https://twitter.com/PetrSvihlik/status/1059776942537392129)!

Please fill out your [postal address](https://goo.gl/forms/gRnURSDlXMX4ctRZ2) if you are interested.

_This comment was automatically generated. If you've submitted more than one pull request, it's OK to fill out the form just once._

Kentico Developer Community

_If there’s anything we can do to help, please don’t hesitate to reach out to us at developerscommunity@kentico.com_

**Comment by fluffynuts** [comment]
@Simply007 hey, thanks! I appreciate it & have filled out the form (:

File: src/components/Articles.vue (hunk 1 above)
Comment (fluffynuts) [reply src/components/Articles.vue]: Just wondering about the style preference here:

1. localised, repeated code vs
2. DRY code with bound functions

each have their merits -- the final style choice is up to a project owner (:

Comment (Simply007) [reply src/components/Articles.vue]: Sorry, for the delay @fluffynuts.
I would prefer local mapping - since the "viewmodel"  is a bit different for Article and Articles - one is using `summary` and the other `body_copy` element.

Comment (fluffynuts) [reply src/components/Articles.vue]: @Simply007 no worries -- I've pushed a commit to address this (:

**Comment by Simply007** [comment]
Hello @fluffynuts,

I have gone through the changes you have made and I have tried to show you, how to implement guarding for all the occurrences of article data (home page, articles and article detail).

I have created a pull request to your branch:
* https://github.com/fluffynuts/cloud-sample-app-vue/pull/1

Go through the changes I have made and then please polish the code:
* remove hardcoded projectId and preview API key from `Client.js`

I have also provided a vue.cli.config for easies debugging:
* you can try it by this tutorial https://vuejs.org/v2/cookbook/debugging-in-vscode.html

Hope that would be usefull!

After you approve the pull request to your branch and remove hardcoded API keys I am more than happy to merge this pull request!

**Comment by fluffynuts** [comment]
@Simply007 I've merged in your branch -- I remember thinking that I needed to remember _not_ to include client & project id's -- and then I did anyway *facepalm*. But that makes me think -- wouldn't it make sense to perhaps get those bits of information from another file which is mentioned in .gitignore? I would imagine that a company would really prefer not to make the mistake that I just did, letting their secrets out into the wild.
I tried reading from `process.env`, but that didn't work out-the-box -- not sure if there's a "proper" way to do that, since I didn't find a definitive answer from a quick web search. Thoughts?

File: src/components/LatestArticles.vue [hunk 2]
```diff
@@ -13,11 +13,16 @@
             <div class="col-md-12 col-lg-6">
                 <router-link :to="articlesData[0].link">
                     <img
+                        v-if="articlesData.imageLink"
```
Comment (Simply007) [inline src/components/LatestArticles.vue]: I am sorry @fluffynuts  - copy-paste error :/ there should be the iterator to point to the first article
```suggestion
                        v-if="articlesData[0].imageLink"
```

**Comment by Simply007** [comment]
I have also created an issue #23 for API key extraction.

**Comment by Simply007** [comment]
I have decided to merge your pull request and then fix the latest articles in a separate one, to have the feature in place.

Thanks @fluffynuts for contribution!

File: src/components/LatestArticles.vue (hunk 2 above)
Comment (Simply007) [reply src/components/LatestArticles.vue]: I have created a pull request on that #24.
